name: Build Zig package
on: 
  push:
  workflow_dispatch:

jobs:
  clang-x64:
    name: Build Skia

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - name: "Clone skia"
        run: git clone --depth 1 https://github.com/mono/skia.git skia_repo
      - name: "Build skia"
        run: |
          clang --version

          cd skia_repo
          python3 tools/git-sync-deps
          python3 bin/fetch-ninja
          bin/gn gen out/lib --args='
            target_os="linux"
            target_cpu="x64"
            is_debug=false
            is_component_build=false
            is_static_skiasharp=true
            is_official_build=true
            skia_enable_gpu=true
            skia_enable_pdf=true
            skia_enable_tools=false
            skia_enable_skottie=false
            skia_use_system_freetype2=false
            skia_use_system_libjpeg_turbo=false
            skia_use_system_libpng=false
            skia_use_system_libwebp=false
            skia_use_system_zlib=false
            skia_enable_discrete_gpu=true
            skia_use_harfbuzz=false
            skia_use_icu=false
            skia_use_sfntly=false
            skia_use_expat=false
            skia_use_piex=true
            skia_use_vulkan=true
            cc="clang"
            cxx="clang++"
          '
          third_party/ninja/ninja -C out/lib skia
          
          mkdir -p ../skia/lib
          cp --recursive include ../skia/include
          cp --recursive out/lib/*.a ../skia/lib
          
          cd ..
          rm -rf skia_repo
          rm -rf .* 2>/dev/null
          ls -lah
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: "Generate zig source"
        run: sh generate.sh
      - name: Archive the build
        uses: actions/upload-artifact@v4
        with:
          name: skia-zig-package
          path: .
