name: Build with MinGW GCC
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  mingw64-gcc:
    name: Build Skia with MinGW GCC

    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: "Setup"
        run: |
          gcc --version

      - name: "Clone skia"
        run: git clone --depth 1 https://github.com/mono/skia.git
      - name: "Build skia"
        run: |
          cd skia
          python3 tools/git-sync-deps
          python3 bin/fetch-ninja
          bin/gn gen out/Static --args='is_official_build=true'
          tree
          bin/ninja -C out/Static skia