name: Build with MinGW GCC
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  mingw64-x64:
    name: Build Skia with MinGW GCC

    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-clang mingw-w64-x86_64-lld

      - name: "Clone skia"
        run: git clone --depth 1 https://github.com/mono/skia.git
      - name: "Build skia"
        run: |
          "${{ steps.msys2.outputs.msys2-location }}/mingw64/bin/clang" --version
          cd skia
          python3 tools/git-sync-deps
          python3 bin/fetch-ninja
          bin/gn gen out/lib --args='
            target_os="win"
            target_cpu="x64"
            is_debug=false
            is_trivial_abi=false
            is_component_build=true
            is_official_build=true
            use_sysroot=false
            skia_enable_fontmgr_win=true
            skia_enable_gpu=true
            skia_enable_pdf=true
            skia_use_freetype=false
            skia_use_system_libjpeg_turbo=false
            skia_use_system_libpng=false
            skia_use_system_libwebp=false
            skia_use_system_zlib=false
            skia_enable_discrete_gpu=true
            skia_use_harfbuzz=false
            skia_use_icu=false
            skia_enable_tools=false
            skia_use_expat=false
            skia_enable_skottie=false
            skia_canvaskit_enable_skottie=false
            skia_canvaskit_enable_embedded_font=false
            skia_canvaskit_enable_paragraph=false
            skia_canvaskit_enable_font=false
            skia_canvaskit_enable_canvas_bindings=false
            skia_enable_spirv_validation=false
            skia_enable_vulkan_debug_layers=false
            skia_use_ffmpeg=false
            skia_use_fontconfig=false
            skia_use_gl=true
            skia_use_libheif=false
            skia_use_lua=false
            skia_enable_skshaper_tests=false
            clang_win="${{ steps.msys2.outputs.msys2-location }}/mingw64"
            clang_win_version=18
            cc="${{ steps.msys2.outputs.msys2-location }}/mingw64/bin/clang"
            cxx="${{ steps.msys2.outputs.msys2-location }}/mingw64/bin/clang++"
          '
          bin/gn args out/lib --list
          third_party/ninja/ninja -C out/lib
          mkdir -p ../lib/skia/win-x64/lib
          cp --recursive include ../lib/skia/win-x64/include
          cp --recursive out/lib/* ../lib/skia/win-x64/lib
          ls out/lib
      - name: Archive the build
        uses: actions/upload-artifact@v4
        with:
          name: windows-mingw64-x64
          path: lib
